import numpy as np
from models.logistic_regression.model import LogisticRegression
from sklearn import linear_model
from metrics.regression import accuracy
#Data generated by AI to test
X = np.array([
    [20, 2000],
    [25, 2200],
    [30, 2500],
    [35, 3000],
    [40, 3200],
    [22, 1800],
    [28, 2400],
    [33, 2800],
    [45, 5000],
    [50, 6000]
])
X_test = np.array([
    [18, 1800],
    [19, 1900],
    [21, 2100],
    [23, 2200],
    [24, 2500],
    [26, 2400],
    [27, 2600],
    [29, 2700],
    [31, 3000],
    [33, 3200],

    # ambiguous / noisy points
    [28, 2000],  # should be 0 but looks like 1
    [30, 2300],  # borderline
    [32, 2100],  # confusing
    [35, 2800],  # overlap
    [36, 2900],

    # high class
    [40, 4500],
    [42, 4700],
    [45, 5000],
    [48, 5200],
    [50, 6000]
])

y_test = np.array([
    0,0,0,0,0,0,0,0,0,0,
    0,0,0,1,1,
    1,1,1,1,1
])
y = np.array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1])
LR = LogisticRegression()

LR.fit(X,y)
prediction = LR.predict(X_test)
print(f"My model : {accuracy(y_test,prediction)}")

LR2 = linear_model.LogisticRegression()
LR2.fit(X,y)
pred2 = LR2.predict(X_test)
print(f"Model from sklearn {accuracy(y_test,pred2)}")